const DEFAULT_DATA={sites:[{id:'demo-a',name:'演示站A',stage:'远程监管生产',days:6,auto:639,manual:59,abnormal:9,score:8},{id:'demo-b',name:'演示站B',stage:'车上接管生产',days:7,auto:507,manual:110,abnormal:12,score:6},{id:'demo-c',name:'演示站C',stage:'已交付',days:5,auto:421,manual:36,abnormal:4,score:9}],reports:[{id:'r29',label:'2026年第29周',site:'demo-a',note:'本周自动化运行稳定，建议继续关注生产任务接管率。',image:'',metrics:[['AI时长接管率',91.78,90,'%','+12.75%'],['生产任务接管率',60.67,80,'%','-10.37%'],['任务成功率',98.61,96,'%','+1.02%'],['有效运营时间',51.48,55,'h','+24.3h'],['累计上料数',698,650,'次','+187次'],['人效比',91.65,90,'%','+1.75%']]},{id:'r28',label:'2026年第28周',site:'demo-b',note:'演示周报：部分指标仍有提升空间。',image:'',metrics:[['AI时长接管率',79.76,80,'%','-4.21%'],['生产任务接管率',81.42,90,'%','+8.14%'],['任务成功率',97.18,96,'%','+0.62%'],['有效运营时间',24.53,65,'h','-12.4h'],['累计上料数',243,550,'次','-268次'],['人效比',76.83,80,'%','-3.10%']]}],memos:{'2026-08-06':'演示站A：自动化运行平稳。'}};
let data=loadData(),currentSite=data.sites[0].id,currentReport=data.reports[0].id;
function clone(v){return JSON.parse(JSON.stringify(v))}
function loadData(){try{const raw=localStorage.getItem('loader-ops-frontend-demo');return raw?JSON.parse(raw):clone(DEFAULT_DATA)}catch{return clone(DEFAULT_DATA)}}
function saveData(){localStorage.setItem('loader-ops-frontend-demo',JSON.stringify(data));document.querySelector('#storageState').textContent='已保存到当前浏览器'}
function esc(v){return String(v).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}
function page(name){document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===name));document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+name));if(name==='overview')renderOverview();if(name==='reports')renderReports();if(name==='calendar')renderCalendar()}
function fmt(v,u){return u==='%'?Number(v).toFixed(2)+'%':u==='h'?Number(v).toFixed(1)+' h':Math.round(v)+' 次'}
function renderOverview(){const s=data.sites.find(x=>x.id===currentSite)||data.sites[0];document.querySelector('#siteSelect').value=s.id;document.querySelector('#summaryGrid').innerHTML=[['运营天数',s.days+'天','本周有运营记录'],['自动上料',s.auto+'次','较上周 +18.4%'],['手动上料',s.manual+'次','占总上料 8.5%'],['自动化异常',s.abnormal+'次',s.abnormal<10?'低于预警线':'需要关注']].map(x=>`<div class="summary"><span>${x[0]}</span><strong>${x[1]}</strong><small class="${x[0]==='自动化异常'&&s.abnormal>=10?'down':'up'}">${x[2]}</small></div>`).join('');document.querySelector('#siteList').innerHTML=data.sites.map(x=>`<div class="site-row"><div><strong>${esc(x.name)}</strong><span>${esc(x.stage)} · ${x.days}天运营</span></div><div><i class="status-dot"></i><span>${x.score}/9 达标</span></div></div>`).join('');document.querySelector('#trendChart').innerHTML=Array.from({length:7},(_,i)=>{const h=42+i*7+(s.id==='demo-b'?-10:0),r=44+i*5;return `<div class="bar-day"><div class="bar hours" style="height:${h}%"></div><div class="bar rate" style="height:${r}%"></div><span class="bar-label">周${i+1}</span></div>`}).join('')}
function renderReports(){const r=data.reports.find(x=>x.id===currentReport)||data.reports[0];if(!r)return;document.querySelector('#reportTabs').innerHTML=data.reports.map(x=>`<button class="report-tab ${x.id===r.id?'active':''}" data-report="${x.id}">${esc(x.label)}</button>`).join('');document.querySelector('#reportTitle').textContent=r.label+' · '+(data.sites.find(x=>x.id===r.site)?.name||'演示站');document.querySelector('#reportScore').textContent='目标指标 '+r.metrics.filter(x=>x[1]>=x[2]).length+' / '+r.metrics.length+' 达标';document.querySelector('#reportMetrics').innerHTML=r.metrics.map(x=>{const ratio=Math.min(100,x[2]?x[1]/x[2]*100:0),state=x[1]>=x[2]?'up':'down';return `<div class="report-metric"><span>${esc(x[0])}</span><b>${fmt(x[1],x[3])}</b><small>目标 ${fmt(x[2],x[3])} · 环比 <em class="${x[4][0]==='-'?'down':'up'}">${esc(x[4])}</em></small><div class="metric-track"><i style="--tone:${state==='up'?'var(--green)':'var(--red)'};width:${ratio}%"></i></div></div>`}).join('');document.querySelector('#noteInput').value=r.note||'';const img=document.querySelector('#imagePreview');img.src=r.image||'';document.querySelector('#imageDrop').classList.toggle('has-image',Boolean(r.image))}
function renderCalendar(){document.querySelector('#calendarGrid').innerHTML=Array.from({length:14},(_,i)=>{const d=new Date(2026,7,1+i),key=d.toISOString().slice(0,10),memo=data.memos[key];return `<div class="day ${i>6?'muted-day':''}"><strong>${d.getMonth()+1}月${d.getDate()}日</strong>${memo?`<p>${esc(memo)}</p><b>有备注</b>`:'<p>暂无演示备注</p>'}</div>`}).join('')}
document.querySelectorAll('.nav').forEach(x=>x.addEventListener('click',()=>page(x.dataset.page)));document.querySelector('#siteSelect').addEventListener('change',e=>{currentSite=e.target.value;renderOverview()});document.querySelector('#resetBtn').addEventListener('click',()=>{if(confirm('确定重置本地演示数据吗？')){localStorage.removeItem('loader-ops-frontend-demo');data=loadData();currentSite=data.sites[0].id;currentReport=data.reports[0].id;renderOverview()}});document.querySelector('#reportTabs').addEventListener('click',e=>{const b=e.target.closest('[data-report]');if(b){currentReport=b.dataset.report;renderReports()}});document.querySelector('#saveNoteBtn').addEventListener('click',()=>{const r=data.reports.find(x=>x.id===currentReport);r.note=document.querySelector('#noteInput').value;saveData();renderReports()});document.querySelector('#addMemoBtn').addEventListener('click',()=>{const key='2026-08-06';data.memos[key]=(data.memos[key]||'')+' 新增一条本地演示备注。';saveData();renderCalendar()});document.querySelector('#addReportBtn').addEventListener('click',()=>{const id='demo-'+Date.now();data.reports.push({id,label:'新增演示周报',site:currentSite,note:'新建的本地演示周报。',image:'',metrics:data.reports[0].metrics.map(x=>[...x])});currentReport=id;saveData();renderReports()});document.querySelector('#imageInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;if(f.size>3*1024*1024){alert('Demo图片不能超过3MB');return}const reader=new FileReader();reader.onload=()=>{const r=data.reports.find(x=>x.id===currentReport);r.image=reader.result;saveData();renderReports()};reader.readAsDataURL(f)});document.querySelector('#clearImageBtn').addEventListener('click',()=>{const r=data.reports.find(x=>x.id===currentReport);r.image='';saveData();renderReports()});document.querySelector('#imageDrop').addEventListener('dragover',e=>e.preventDefault());document.querySelector('#imageDrop').addEventListener('drop',e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f){const input=document.querySelector('#imageInput');const reader=new FileReader();reader.onload=()=>{const r=data.reports.find(x=>x.id===currentReport);r.image=reader.result;saveData();renderReports()};reader.readAsDataURL(f)}});
const select=document.querySelector('#siteSelect');select.innerHTML=data.sites.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');renderOverview();
